### ISSUE TITLE
Urgent Drupal 7 API upgrade requirements

### ISSUE THREAD

**Issue by rfay** [warmshowers/WarmShowers-Windows#46]
Hi Kurt - Please read https://github.com/warmshowers/Warmshowers.org/issues/555 to understand the urgent requirement for changes to the IOS app. If we can get these in now, hopefully most of our users will have working apps in the fall.

Thanks!
-Randy

**Comment by klzig** [comment]
Randy, it looks like the D7 API may include changes to Privatemsg.  Are the old calls being deprecated?  I don't think I need the proposed changes but if I'm wrong about that I'll need to test against the new API before I can release an updated app.

**Comment by rfay** [comment]
The api should be as documented in the Wiki. I don't know what you're
currently using of course. But please don't make a release without
supporting the d7 token at any rate because it would be very soon obsolete.

**Comment by rfay** [comment]
Sorry I was so terse, but am tapping answers out on a phone in a campground
in Southern Oregon. The Wiki is
https://github.com/warmshowers/Warmshowers.org/wiki/Warmshowers-RESTful-Services-for-Mobile-Apps

You should be able to test any api using a tool like Postman to make sure
everything behaves as documented. There was a new iOS app recently so we
worked through the messaging stuff and had to make sure it worked.

Hi from near Crater Lake in Southern Oregon. We've been on our tandem about
900 miles from northern Washington and think we'll drop down to the coast
from Crater Lake and do the California coast to San Francisco then go home.
We'll be back about September 1 and the Drupal 7 upgrade will proceed
rapidly at that point (and I can support you easier).

I should note that the d7 staging site, set up for apps to test with,
currently has basic auth on it to prevent google discovering it. So if you
need it soon we can white list your apps user-agent string.

Thanks for all the work on this!

-Randy

**Comment by klzig** [comment]
I’d seen some of your comments from the github site so thought maybe you weren’t traveling yet.   Enjoy!

 

That’s the wiki I’m using (I don’t know of any other).  My concern about the messaging comes from the section I pasted at the end of this email.  The WP app has been working for a long time without this change so I just wanted to make sure the original Privatemsg APIs aren’t going away.

 

I’ve already verified my use of the APIs but can’t be completely sure I’m handling the new token properly until I’m hitting a server that requires it.  Seems straightforward, I don’t expect any problems, and can test that whenever you can get me access to the staging server.  My user-agent string appears to be NativeHost.  I don’t intentionally set it and have never before looked at what the app is spitting out for this, but this is what Fiddler is currently telling me.

 

Regarding the host picture, in playing around with this some more I notice that ‘picture’ (what I’ve been using) yields a much higher-resolution pic than either of the  ‘profile_image…’ keys in the new GET /services/rest/user/<UID> API.   I lazy-load the host picture so am not too concerned about delay, I’d rather wait (or not) for a good pic than get a grainy/cropped one quickly.  So unless the plan is to deprecate ‘picture’ from the API I’ll keep using it.
 
I’m about done with the D7 changes and can do some final tests whenever you can get me access to the staging server.  After you return should be fine.  It would be nice to have a couple of weeks between testing against the staging server and going live with D7, to give me time to get the app through the Microsoft approval process.  I’ll start that process in the next week or so, so if the final testing looks good I can have the app in the store in a day.
 
kurt

 

 

Drupal 7 Privatemsg Messages API Changes

** experimental, not in effect yet **

Access inbox: GET /services/rest/message

Access a single message: GET /services/rest/message/MESSAGE_ID

Create a new message thread (if thread_id is empty) or reply to a thread (if thread_id is provided) POST /services/rest/message

with 

·         body

·         recipients (username)

·         subject

·         thread_id

**Comment by klzig** [comment]
All five D7 migration issues are addressed.  Waiting for access to staging server (September is fine) for final testing.
